name: Si Gross Nature Space
favicon: null
layout_spectrum: 0.9683893909677863
typography_spectrum: 0.25882
title: Si Gross Nature Space
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#06050a'
    - '#575759'
    - '#d5d5d7'
    - '#878789'
  brandStrength: 0.8535838583484292
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
